// <auto-generated />
using System;
using AtTheSeams.Data.Connections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtTheSeams.Data.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20250221014125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("AtTheSeams.Data.Models.ClientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AtTheSeams.Data.Models.ClientMeasurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A_ChestMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("B_SeatMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("C_WaistMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("D_TrouserMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("E_F_HalfBackMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("E_I_SleeveLengthTwoPieceMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("G_H_BackNeckToWaistMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("G_I_SyceDepthMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("I_L_SleeveLengthOnePieceMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("N_InsideLegMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P_Q_BodyRiseMeasurement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("R_CloseWristMeasurement")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("AtTheSeams.Data.Models.ClientMeasurements", b =>
                {
                    b.HasOne("AtTheSeams.Data.Models.ClientInfo", "Client")
                        .WithMany("Measurements")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AtTheSeams.Data.Models.ClientInfo", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
